### PR TITLE
General Cleanup

### PR DESCRIPTION
**Pull request by infininight**
Made quite a few changes as I was reviewing the bundle for inclusion into the bundle installer. Got some complaints about the current Scala bundle we have which is very outdated, found yours when doing research into it. Will switch to yours once these changes are pulled in.

### CODE REVIEW

**Comment by refried** [comment]
This PR is a year old; what's going on with it?

@infininight do you know of a more maintained version?

**Comment by infininight** [comment]
@refried Thanks for poking this. Since this has gone un-merged I've forked the bundle under the textmate user and updated the bundle installer to use that fork. The bundle should update in TextMate within a few hours automatically.

**Comment by refried** [comment]
@infininight Github's syntax highlighter for scala uses this version.  I ended up here because I have a highlighting bug I’d like to have fixed.  May I raise the issue on your fork and also try to direct Github to use to yours? :)

**Comment by refried** [comment]
@infininight Ok, great, thanks.  Yes I saw that issue too and certainly, with the size of the linked files, the issue was not obvious.  I will try to distill mine and theirs to something useful.  I'm very familiar with Scala, but not at all familiar with .tmbundles, so maybe we will make a good team ;-)

**Comment by refried** [comment]
@infininight Huh.  I guess that by default, forks (e.g. your textmate user fork) don't have their own issues list.  Do you want to enable it (https://github.com/textmate/scala.tmbundle/settings) or should I create issues here?

**Comment by infininight** [comment]
@refried Yeah forks intentionally don't by default to centralize the conversations. I've enabled them now. :)

**Comment by mads-hartmann** [comment]
@infininight  @refried Somehow I never got a notification about this PR 😱 Sorry about that. Merging it now, even tough I realise it's waaaay too late

**Pull request merged**
